# Generated by Django 5.2.11 on 2026-03-05 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentresult',
            name='feedback',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='feedback.feedback'),
        ),
    ]
