# Generated by Django 5.2.12 on 2026-03-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentresult',
            name='aspect_sentiments',
            field=models.JSONField(blank=True, default=dict, help_text='Per-aspect sentiment: {aspect: {polarity, label, phrases}}'),
        ),
        migrations.AddField(
            model_name='sentimentresult',
            name='emotions',
            field=models.JSONField(blank=True, default=dict, help_text='Emotion scores: {emotion_name: score}'),
        ),
    ]
