# Generated by Django 5.2.12 on 2026-04-02 09:36

from django.db import migrations, models


def blank_to_null(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.filter(enrollment_no='').update(enrollment_no=None)
    CustomUser.objects.filter(faculty_id='').update(faculty_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        # Step 1: Add null=True without unique (so blanks can become NULL)
        migrations.AlterField(
            model_name='customuser',
            name='enrollment_no',
            field=models.CharField(blank=True, help_text='For students only', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='faculty_id',
            field=models.CharField(blank=True, help_text='For faculty only', max_length=20, null=True),
        ),
        # Step 2: Convert blank strings to NULL
        migrations.RunPython(blank_to_null, migrations.RunPython.noop),
        # Step 3: Now add unique constraint
        migrations.AlterField(
            model_name='customuser',
            name='enrollment_no',
            field=models.CharField(blank=True, help_text='For students only', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='faculty_id',
            field=models.CharField(blank=True, help_text='For faculty only', max_length=20, null=True, unique=True),
        ),
    ]
