# Generated by Django 5.2.12 on 2026-03-29 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('livefeedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='session_type',
            field=models.CharField(choices=[('class', 'Class'), ('hackathon', 'Hackathon'), ('masterclass', 'Masterclass'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('other', 'Other')], default='class', max_length=20),
        ),
        migrations.AddField(
            model_name='livesession',
            name='title',
            field=models.CharField(blank=True, help_text='Custom title for non-subject sessions', max_length=200),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='courses.subject'),
        ),
    ]
