# Generated by Django 5.2.12 on 2026-03-29 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('feedback', '0002_feedbackresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('semester', models.IntegerField(blank=True, help_text='Target specific semester. Leave blank for all semesters.', null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, help_text='Target specific program. Leave blank for all programs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_campaigns', to='courses.program')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Campaign this feedback was submitted under (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='feedback.feedbackcampaign'),
        ),
    ]
